//
// Generated file, do not edit! Created by nedtool 5.6 from pingpong.msg.
//

#ifndef __PINGPONG_M_H
#define __PINGPONG_M_H

#if defined(__clang__)
#  pragma clang diagnostic ignored "-Wreserved-id-macro"
#endif
#include <omnetpp.h>

// nedtool version check
#define MSGC_VERSION 0x0506
#if (MSGC_VERSION!=OMNETPP_VERSION)
#    error Version mismatch! Probably this file was generated by an earlier version of nedtool: 'make clean' should help.
#endif



/**
 * Class generated from <tt>pingpong.msg:2</tt> by nedtool.
 * <pre>
 * message PingPongMsg
 * {
 *     int source;
 *     int destination;
 *     int hopCount = 0;
 * }
 * </pre>
 */
class PingPongMsg : public ::omnetpp::cMessage
{
  protected:
    int source;
    int destination;
    int hopCount;

  private:
    void copy(const PingPongMsg& other);

  protected:
    // protected and unimplemented operator==(), to prevent accidental usage
    bool operator==(const PingPongMsg&);

  public:
    PingPongMsg(const char *name=nullptr, short kind=0);
    PingPongMsg(const PingPongMsg& other);
    virtual ~PingPongMsg();
    PingPongMsg& operator=(const PingPongMsg& other);
    virtual PingPongMsg *dup() const override {return new PingPongMsg(*this);}
    virtual void parsimPack(omnetpp::cCommBuffer *b) const override;
    virtual void parsimUnpack(omnetpp::cCommBuffer *b) override;

    // field getter/setter methods
    virtual int getSource() const;
    virtual void setSource(int source);
    virtual int getDestination() const;
    virtual void setDestination(int destination);
    virtual int getHopCount() const;
    virtual void setHopCount(int hopCount);
};

inline void doParsimPacking(omnetpp::cCommBuffer *b, const PingPongMsg& obj) {obj.parsimPack(b);}
inline void doParsimUnpacking(omnetpp::cCommBuffer *b, PingPongMsg& obj) {obj.parsimUnpack(b);}


#endif // ifndef __PINGPONG_M_H

